exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: Home is Here  # your site title
subtitle: A Personal Guide to Your First Home  # your site subtitle
url: "http:/www.homeishere.ca" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.svg"

# Build settings
markdown: kramdown

# sass
sass:
  sass_dir: _sass
  # style:            compressed
# Use collections dir
collections_dir: collections
collections:
    # notes:
    #     permalink: /:categories/:title
    #     output: true
    # courses:
    #     permalink: /:name
    #     output: true
    faqs:
        ouput: false
    checklists:
        permalink: /en/home-buyer-checklist/:slug
        output: true
    checklistskr:
        permalink: /kr/home-buyer-checklist/:slug
        output: true

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
